#!/bin/bash

test -d lib || mkdir lib
test -f deps.txt || exit

for line in `cat deps.txt`; do
  groupId=$(echo $line | rev | cut -d'-' -f2- | cut -d'.' -f2- | rev)
  artifactId=$(echo $line | rev | cut -d'-' -f2- | cut -d'.' -f1 | rev)
  version=$(echo $line | rev | cut -d'-' -f1 | cut -d'.' -f2- | rev)
  
  echo curl http://github.sogou-op.org/qiyun/extlib/raw/master/$line -o lib/$line | bash -x
  echo mvn install:install-file -Dfile=./lib/$line -DgroupId=$groupId -DartifactId=$artifactId -Dversion=$version -Dpackaging=jar | bash -x
done
